server:
  port: ${HOST_PORT:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: retail-service
  jpa:
    hibernate:
      ddl-auto: ${DDL_METHOD:update}
  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/retail?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mysql://wisata-lembang.com:3306/u8128384_retail?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: ${MYSQL_USER:root}
    username: u8128384_retailadm
#    password: ${MYSQL_PASSWORD:}
    password: ilhamgibran
    driver-class-name: com.mysql.jdbc.Driver